import '../order_model.dart';

class Data {
  List<OrderModel> orderlist = [
    OrderModel(
      orderStatus: 'Delivered on Dec 02, 2021',
      orderdescription:
          'METRONAUT Athleisure Printed Men Round or Crew Grey T-Shirt',
      imageUrl:
          'https://rukminim1.flixcart.com/image/714/857/jiqb8nk0/t-shirt/a/w/x/m-m7ss18tee016a-metronaut-original-imaf6ggqbed75ffr.jpeg?q=50',
      rating: null,
      amount: '549',
      colorAvailable: 'Grey, White',
      orderDate: 'Mon, 30th Nov\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 549,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Nov 01, 2021',
      orderdescription: 'Skull Candy Method Bluetooth Headset with MIC',
      imageUrl:
          'https://www.zebrs.com/uploads/zebrs/products/1-883967_l.jpg?param=1',
      rating: 4,
      amount: '2599',
      colorAvailable: 'Blue, Red',
      orderDate: 'Wed, 27th Oct\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 2599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Oct 24, 2021',
      orderdescription:
          'Lenevo Ideapad 320E Core i3 6th Gen - (4GB/1TB HDD/Windows)',
      imageUrl:
          'https://www.lenovo.com/medias/lenovo-laptop-ideapad-3-15-intel-feature-1.png?context=bWFzdGVyfHJvb3R8MjA1MzczfGltYWdlL3BuZ3xoYmMvaDMxLzEwNzU3MjQxNjAyMDc4LnBuZ3w5NmJjYjk0ZGIwZTc4MzhhNzBlYjBhNTZmYjA2Yjg0NzkzZWE5ZjM4YWE3YWQ1N2QxMzMzYmQ2NzUyYmYyODE1&w=1920',
      rating: 2,
      amount: '39999',
      colorAvailable: 'Grey',
      orderDate: 'Tue, 20th Oct\'21',
      orderID: 'duedy736e37wdgdg499',
      sellingPrice: 39999,
      shippingDiscount: 100,
      shippingFee: 100,
    ),
    OrderModel(
      orderStatus: 'Delivered on Sep 12, 2021',
      orderdescription:
          'boAt Airdopes 131 Bluetooth Headset(Active Black, True Wireless)',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS9uOYR8aWiZ03rr-cHMntOokbxeihUtx0Kw&usqp=CAU',
      rating: null,
      amount: '3599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sat, 7th Sep\'21',
      orderID: 'duedy736e37wdgdg272',
      sellingPrice: 3599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Aug 20, 2021',
      orderdescription: 'Flipkart SmartBuy KD503 Universal Active Stylus',
      imageUrl:
          'https://rukminim1.flixcart.com/image/312/312/ksdjma80/stylus/r/7/k/stylus-pen-for-ipad-with-palm-rejection-tilt-sensor-2nd-gen-original-imag5ycuxpmtyxyr.jpeg?q=70',
      rating: 5,
      amount: '5599',
      colorAvailable: 'Black, White',
      orderDate: 'Fri, 15th Aug\'21',
      orderID: 'duedy736e37wdgdg317',
      sellingPrice: 5599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Jul 05, 2021',
      orderdescription:
          'HAVELLS Capture Multi Cooker Electric Kettle  (1.2 L, Green)',
      imageUrl:
          'https://rukminim1.flixcart.com/image/416/416/kuk4u4w0/electric-kettle/r/y/o/capture-1-2-havells-original-imag7ne5qv3yzck2.jpeg?q=70',
      rating: 3,
      amount: '1599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sun, 1st Jul\'21',
      orderID: 'duedy736e37wdgdg928',
      sellingPrice: 1599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Jun 18, 2021',
      orderdescription:
          'Mens Comfortable Trending And Stylish Multicolor Embozing Slipper And Flipflop (Pack Of 2) Slippers  (Multicolor 10)',
      imageUrl:
          'https://rukminim1.flixcart.com/image/800/960/ks7tuvk0/slipper-flip-flop/m/e/n/10-fe-384wt-384br-footup-multicolor-9-original-imag5u4wjcwzncfh.jpeg?q=50',
      rating: 1,
      amount: '449',
      colorAvailable: 'Orange, SkyBlue',
      orderDate: 'Mon, 15th June\'21',
      orderID: 'duedy736e37wdgdg839',
      sellingPrice: 449,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on May 01, 2021',
      orderdescription:
          'A1323 Youth Analog ( MCW-200H-2AVDF ) Analog Watch - For Men',
      imageUrl:
          'https://rukminim1.flixcart.com/image/800/960/krz97rk0/watch/j/q/6/a1323-casio-original-imag5n4mh8puggv8.jpeg?q=50',
      rating: 3,
      amount: '999',
      colorAvailable: 'Black, Blue',
      orderDate: 'Sat, 30th Apr\'21',
      orderID: 'duedy736e37wdgd738',
      sellingPrice: 999,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Dec 02, 2021',
      orderdescription:
          'METRONAUT Athleisure Printed Men Round or Crew Grey T-Shirt',
      imageUrl:
          'https://rukminim1.flixcart.com/image/714/857/jiqb8nk0/t-shirt/a/w/x/m-m7ss18tee016a-metronaut-original-imaf6ggqbed75ffr.jpeg?q=50',
      rating: null,
      amount: '549',
      colorAvailable: 'Grey, White',
      orderDate: 'Mon, 30th Nov\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 549,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Nov 01, 2021',
      orderdescription: 'Skull Candy Method Bluetooth Headset with MIC',
      imageUrl:
          'https://www.zebrs.com/uploads/zebrs/products/1-883967_l.jpg?param=1',
      rating: 4,
      amount: '2599',
      colorAvailable: 'Blue, Red',
      orderDate: 'Wed, 27th Oct\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 2599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Oct 24, 2021',
      orderdescription:
          'Lenevo Ideapad 320E Core i3 6th Gen - (4GB/1TB HDD/Windows)',
      imageUrl:
          'https://www.lenovo.com/medias/lenovo-laptop-ideapad-3-15-intel-feature-1.png?context=bWFzdGVyfHJvb3R8MjA1MzczfGltYWdlL3BuZ3xoYmMvaDMxLzEwNzU3MjQxNjAyMDc4LnBuZ3w5NmJjYjk0ZGIwZTc4MzhhNzBlYjBhNTZmYjA2Yjg0NzkzZWE5ZjM4YWE3YWQ1N2QxMzMzYmQ2NzUyYmYyODE1&w=1920',
      rating: 2,
      amount: '39999',
      colorAvailable: 'Grey',
      orderDate: 'Tue, 20th Oct\'21',
      orderID: 'duedy736e37wdgdg499',
      sellingPrice: 39999,
      shippingDiscount: 100,
      shippingFee: 100,
    ),
    OrderModel(
      orderStatus: 'Delivered on Sep 12, 2021',
      orderdescription:
          'boAt Airdopes 131 Bluetooth Headset(Active Black, True Wireless)',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS9uOYR8aWiZ03rr-cHMntOokbxeihUtx0Kw&usqp=CAU',
      rating: null,
      amount: '3599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sat, 7th Sep\'21',
      orderID: 'duedy736e37wdgdg272',
      sellingPrice: 3599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Aug 20, 2021',
      orderdescription: 'Flipkart SmartBuy KD503 Universal Active Stylus',
      imageUrl:
          'https://rukminim1.flixcart.com/image/312/312/ksdjma80/stylus/r/7/k/stylus-pen-for-ipad-with-palm-rejection-tilt-sensor-2nd-gen-original-imag5ycuxpmtyxyr.jpeg?q=70',
      rating: 5,
      amount: '5599',
      colorAvailable: 'Black, White',
      orderDate: 'Fri, 15th Aug\'21',
      orderID: 'duedy736e37wdgdg317',
      sellingPrice: 5599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Jul 05, 2021',
      orderdescription:
          'HAVELLS Capture Multi Cooker Electric Kettle  (1.2 L, Green)',
      imageUrl:
          'https://rukminim1.flixcart.com/image/416/416/kuk4u4w0/electric-kettle/r/y/o/capture-1-2-havells-original-imag7ne5qv3yzck2.jpeg?q=70',
      rating: 3,
      amount: '1599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sun, 1st Jul\'21',
      orderID: 'duedy736e37wdgdg928',
      sellingPrice: 1599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Jun 18, 2021',
      orderdescription:
          'Mens Comfortable Trending And Stylish Multicolor Embozing Slipper And Flipflop (Pack Of 2) Slippers  (Multicolor 10)',
      imageUrl:
          'https://rukminim1.flixcart.com/image/800/960/ks7tuvk0/slipper-flip-flop/m/e/n/10-fe-384wt-384br-footup-multicolor-9-original-imag5u4wjcwzncfh.jpeg?q=50',
      rating: 1,
      amount: '449',
      colorAvailable: 'Orange, SkyBlue',
      orderDate: 'Mon, 15th June\'21',
      orderID: 'duedy736e37wdgdg839',
      sellingPrice: 449,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on May 01, 2021',
      orderdescription:
          'A1323 Youth Analog ( MCW-200H-2AVDF ) Analog Watch - For Men',
      imageUrl:
          'https://rukminim1.flixcart.com/image/800/960/krz97rk0/watch/j/q/6/a1323-casio-original-imag5n4mh8puggv8.jpeg?q=50',
      rating: 3,
      amount: '999',
      colorAvailable: 'Black, Blue',
      orderDate: 'Sat, 30th Apr\'21',
      orderID: 'duedy736e37wdgd738',
      sellingPrice: 999,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Dec 02, 2021',
      orderdescription:
          'METRONAUT Athleisure Printed Men Round or Crew Grey T-Shirt',
      imageUrl:
          'https://rukminim1.flixcart.com/image/714/857/jiqb8nk0/t-shirt/a/w/x/m-m7ss18tee016a-metronaut-original-imaf6ggqbed75ffr.jpeg?q=50',
      rating: null,
      amount: '549',
      colorAvailable: 'Grey, White',
      orderDate: 'Mon, 30th Nov\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 549,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Nov 01, 2021',
      orderdescription: 'Skull Candy Method Bluetooth Headset with MIC',
      imageUrl:
          'https://www.zebrs.com/uploads/zebrs/products/1-883967_l.jpg?param=1',
      rating: 4,
      amount: '2599',
      colorAvailable: 'Blue, Red',
      orderDate: 'Wed, 27th Oct\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 2599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Oct 24, 2021',
      orderdescription:
          'Lenevo Ideapad 320E Core i3 6th Gen - (4GB/1TB HDD/Windows)',
      imageUrl:
          'https://www.lenovo.com/medias/lenovo-laptop-ideapad-3-15-intel-feature-1.png?context=bWFzdGVyfHJvb3R8MjA1MzczfGltYWdlL3BuZ3xoYmMvaDMxLzEwNzU3MjQxNjAyMDc4LnBuZ3w5NmJjYjk0ZGIwZTc4MzhhNzBlYjBhNTZmYjA2Yjg0NzkzZWE5ZjM4YWE3YWQ1N2QxMzMzYmQ2NzUyYmYyODE1&w=1920',
      rating: 2,
      amount: '39999',
      colorAvailable: 'Grey',
      orderDate: 'Tue, 20th Oct\'21',
      orderID: 'duedy736e37wdgdg499',
      sellingPrice: 39999,
      shippingDiscount: 100,
      shippingFee: 100,
    ),
    OrderModel(
      orderStatus: 'Delivered on Sep 12, 2021',
      orderdescription:
          'boAt Airdopes 131 Bluetooth Headset(Active Black, True Wireless)',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS9uOYR8aWiZ03rr-cHMntOokbxeihUtx0Kw&usqp=CAU',
      rating: null,
      amount: '3599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sat, 7th Sep\'21',
      orderID: 'duedy736e37wdgdg272',
      sellingPrice: 3599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Aug 20, 2021',
      orderdescription: 'Flipkart SmartBuy KD503 Universal Active Stylus',
      imageUrl:
          'https://rukminim1.flixcart.com/image/312/312/ksdjma80/stylus/r/7/k/stylus-pen-for-ipad-with-palm-rejection-tilt-sensor-2nd-gen-original-imag5ycuxpmtyxyr.jpeg?q=70',
      rating: 5,
      amount: '5599',
      colorAvailable: 'Black, White',
      orderDate: 'Fri, 15th Aug\'21',
      orderID: 'duedy736e37wdgdg317',
      sellingPrice: 5599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Jul 05, 2021',
      orderdescription:
          'HAVELLS Capture Multi Cooker Electric Kettle  (1.2 L, Green)',
      imageUrl:
          'https://rukminim1.flixcart.com/image/416/416/kuk4u4w0/electric-kettle/r/y/o/capture-1-2-havells-original-imag7ne5qv3yzck2.jpeg?q=70',
      rating: 3,
      amount: '1599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sun, 1st Jul\'21',
      orderID: 'duedy736e37wdgdg928',
      sellingPrice: 1599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Jun 18, 2021',
      orderdescription:
          'Mens Comfortable Trending And Stylish Multicolor Embozing Slipper And Flipflop (Pack Of 2) Slippers  (Multicolor 10)',
      imageUrl:
          'https://rukminim1.flixcart.com/image/800/960/ks7tuvk0/slipper-flip-flop/m/e/n/10-fe-384wt-384br-footup-multicolor-9-original-imag5u4wjcwzncfh.jpeg?q=50',
      rating: 1,
      amount: '449',
      colorAvailable: 'Orange, SkyBlue',
      orderDate: 'Mon, 15th June\'21',
      orderID: 'duedy736e37wdgdg839',
      sellingPrice: 449,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on May 01, 2021',
      orderdescription:
          'A1323 Youth Analog ( MCW-200H-2AVDF ) Analog Watch - For Men',
      imageUrl:
          'https://rukminim1.flixcart.com/image/800/960/krz97rk0/watch/j/q/6/a1323-casio-original-imag5n4mh8puggv8.jpeg?q=50',
      rating: 3,
      amount: '999',
      colorAvailable: 'Black, Blue',
      orderDate: 'Sat, 30th Apr\'21',
      orderID: 'duedy736e37wdgd738',
      sellingPrice: 999,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Dec 02, 2021',
      orderdescription:
          'METRONAUT Athleisure Printed Men Round or Crew Grey T-Shirt',
      imageUrl:
          'https://rukminim1.flixcart.com/image/714/857/jiqb8nk0/t-shirt/a/w/x/m-m7ss18tee016a-metronaut-original-imaf6ggqbed75ffr.jpeg?q=50',
      rating: null,
      amount: '549',
      colorAvailable: 'Grey, White',
      orderDate: 'Mon, 30th Nov\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 549,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Nov 01, 2021',
      orderdescription: 'Skull Candy Method Bluetooth Headset with MIC',
      imageUrl:
          'https://www.zebrs.com/uploads/zebrs/products/1-883967_l.jpg?param=1',
      rating: 4,
      amount: '2599',
      colorAvailable: 'Blue, Red',
      orderDate: 'Wed, 27th Oct\'21',
      orderID: 'duedy736e37wdgdg382',
      sellingPrice: 2599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Oct 24, 2021',
      orderdescription:
          'Lenevo Ideapad 320E Core i3 6th Gen - (4GB/1TB HDD/Windows)',
      imageUrl:
          'https://www.lenovo.com/medias/lenovo-laptop-ideapad-3-15-intel-feature-1.png?context=bWFzdGVyfHJvb3R8MjA1MzczfGltYWdlL3BuZ3xoYmMvaDMxLzEwNzU3MjQxNjAyMDc4LnBuZ3w5NmJjYjk0ZGIwZTc4MzhhNzBlYjBhNTZmYjA2Yjg0NzkzZWE5ZjM4YWE3YWQ1N2QxMzMzYmQ2NzUyYmYyODE1&w=1920',
      rating: 2,
      amount: '39999',
      colorAvailable: 'Grey',
      orderDate: 'Tue, 20th Oct\'21',
      orderID: 'duedy736e37wdgdg499',
      sellingPrice: 39999,
      shippingDiscount: 100,
      shippingFee: 100,
    ),
    OrderModel(
      orderStatus: 'Delivered on Sep 12, 2021',
      orderdescription:
          'boAt Airdopes 131 Bluetooth Headset(Active Black, True Wireless)',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS9uOYR8aWiZ03rr-cHMntOokbxeihUtx0Kw&usqp=CAU',
      rating: null,
      amount: '3599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sat, 7th Sep\'21',
      orderID: 'duedy736e37wdgdg272',
      sellingPrice: 3599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Aug 20, 2021',
      orderdescription: 'Flipkart SmartBuy KD503 Universal Active Stylus',
      imageUrl:
          'https://rukminim1.flixcart.com/image/312/312/ksdjma80/stylus/r/7/k/stylus-pen-for-ipad-with-palm-rejection-tilt-sensor-2nd-gen-original-imag5ycuxpmtyxyr.jpeg?q=70',
      rating: 5,
      amount: '5599',
      colorAvailable: 'Black, White',
      orderDate: 'Fri, 15th Aug\'21',
      orderID: 'duedy736e37wdgdg317',
      sellingPrice: 5599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
    OrderModel(
      orderStatus: 'Delivered on Jul 05, 2021',
      orderdescription:
          'HAVELLS Capture Multi Cooker Electric Kettle  (1.2 L, Green)',
      imageUrl:
          'https://rukminim1.flixcart.com/image/416/416/kuk4u4w0/electric-kettle/r/y/o/capture-1-2-havells-original-imag7ne5qv3yzck2.jpeg?q=70',
      rating: 3,
      amount: '1599',
      colorAvailable: 'Grey, White',
      orderDate: 'Sun, 1st Jul\'21',
      orderID: 'duedy736e37wdgdg928',
      sellingPrice: 1599,
      shippingDiscount: 40,
      shippingFee: 40,
    ),
  ];
}
